definitions = {
    'Pharmacodynamics': 'The study of the biochemical and physiological effects of drugs on the body.',
    'Pharmacokinetics': 'The study of how the body affects a drug, including absorption, distribution, metabolism, and elimination.',
    'Half-life': 'The time it takes for the concentration of a drug in the body to be reduced by half.',
    'Bioavailability': 'The proportion of a drug that enters the circulation and is able to have an active effect on the body.',
    'Therapeutic index': 'The ratio of the dose of a drug that produces a therapeutic effect to the dose that produces a toxic effect.',
    'Agonist': 'A drug that activates a receptor to produce a response similar to that of the endogenous ligand.',
    'Antagonist': 'A drug that blocks the action of an agonist by binding to a receptor without producing a response of its own.',
    'Receptor': 'A protein on the surface or inside of a cell that can bind to a drug or other ligand and produce a response.',
    'Tolerance': 'A decreased response to a drug following repeated or prolonged use.',
     "Withdrawal": "The set of symptoms that occur when a person suddenly stops taking a drug to which he or she has become addicted.",
    "Side effect": "An unintended and often unwanted effect of a medication that occurs in addition to its intended effect.",
    "Adverse reaction": "A harmful or unpleasant reaction to a medication, which can range from mild to severe.",
    "Allergic reaction": "An abnormal reaction of the immune system to a medication, which can range from mild to severe and even life-threatening.",
    "Idiosyncratic reaction": "An unusual or unpredictable reaction to a medication that is not related to its intended effect.",
    "Toxicity": "The degree to which a medication can cause harm or damage to the body, often related to the dose and duration of use.",
    "Drug interaction": "The effect of one medication on the effectiveness or toxicity of another medication, often due to changes in the way the body metabolizes the drugs.",
    "Additive effect": "The effect of two drugs used together that is equal to the sum of the effects of each drug used alone.",
    "Synergistic effect": "The effect of two drugs used together that is greater than the sum of the effects of each drug used alone.",
    "Potentiation": "The effect of one drug on the effectiveness of another drug, often due to changes in the way the body metabolizes the drugs."
    'Enzyme inhibition: "The process of decreasing or completely stopping the activity of an enzyme by a drug or other substance.',
    'Enzyme induction': "The process of increasing the activity of an enzyme by a drug or other substance.",
    'Pharmacogenetics': 'The study of how a persons genetic makeup affects their response to drugs.',
    'Compliance': 'The degree to which a patient follows medical advice and takes medication as prescribed.',
    'Dosage': 'The amount of a drug that should be taken at one time or over a period of time.',
    'Route of administration': 'The way in which a drug is taken into the body (e.g. orally, intravenously, topically).',
    'Oral': 'A route of drug administration where the medication is taken by mouth and swallowed.',
    'Topical': 'A route of drug administration where the medication is applied to the surface of the skin or a mucous membrane.',
    'Intravenous': 'A route of drug administration where the medication is injected directly into a vein.',
    'Intramuscular': 'A route of drug administration where the medication is injected into a muscle.',
    'Subcutaneous': 'A route of drug administration where the medication is injected into the fatty tissue beneath the skin.',
     "Inhalation": "The administration of medication by breathing it in through the lungs.",
    "Transdermal": "The administration of medication through the skin, typically via a patch.",
    "Parenteral": "The administration of medication through a route other than the digestive tract, such as by injection or infusion.",
    "Enteral": "The administration of medication through the digestive tract, such as by mouth or feeding tube.",
    "Pharmacist": "A healthcare professional who is trained in the preparation and dispensing of medications.",
    "Drug formulary": "A list of medications that are approved for use within a healthcare system, such as a hospital or insurance plan.",
    "Prescription": "An order written by a healthcare provider for a specific medication to be dispensed to a patient.",
    "Over-the-counter (OTC)": "A medication that is available for purchase without a prescription.",
    "Controlled substance": "A medication that is regulated by the government due to its potential for abuse or addiction.",
     'Schedule I': 'Drugs with no accepted medical use and a high potential for abuse.',
    'Schedule II': 'Drugs with a high potential for abuse, which may lead to severe psychological or physical dependence.',
    'Schedule III': 'Drugs with a moderate to low potential for physical and psychological dependence.',
    'Schedule IV': 'Drugs with a low potential for abuse and low risk of dependence.',
    'Schedule V': 'Drugs with a low potential for abuse and consist of preparations containing limited quantities of certain narcotics.',
    'Black box warning': 'A warning printed on a prescription drugs package insert, indicating that the drug may have serious or life-threatening risks.',
    "Pharmacotherapy": "The use of drugs to treat disease or alleviate symptoms.",
    "Prophylaxis": "The use of drugs to prevent disease or infection.",
    "Toxicology": "The study of the harmful effects of drugs or other substances on living organisms.",
    "Pharmacology": "The study of how drugs affect the body and how the body affects drugs.",
    "Placebo effect": "The phenomenon where a person experiences a beneficial effect from a treatment that has no active ingredients, simply because they believe it will work."
}

