terms = [
    'Pharmacodynamics',
    'Pharmacokinetics',
    'Half-life',
    'Bioavailability',
    'Therapeutic index',
    'Agonist',
    'Antagonist',
    'Receptor',
    'Tolerance',
    'Withdrawal',
    'Side effect',
    'Adverse reaction',
    'Allergic reaction',
    'Idiosyncratic reaction',
    'Toxicity',
    'Drug interaction',
    'Additive effect',
    'Synergistic effect',
    'Potentiation',
    'Enzyme inhibition',
    'Enzyme induction',
    'Pharmacogenetics',
    'Compliance',
    'Dosage',
    'Route of administration',
    'Oral',
    'Topical',
    'Intravenous',
    'Intramuscular',
    'Subcutaneous',
    'Inhalation',
    'Transdermal',
    'Parenteral',
    'Enteral',
    'Pharmacist',
    'Drug formulary',
    'Prescription',
    'Over-the-counter (OTC)',
    'Controlled substance',
    'Schedule I',
    'Schedule II',
    'Schedule III',
    'Schedule IV',
    'Schedule V',
    'Black box warning',
    'Pharmacotherapy',
    'Prophylaxis',
    'Toxicology',
    'Pharmacology',
    'Placebo effect'
]
