medications = [
    'Baclofen',
    'Cyclobenzaprine',
    'Dantrolene',
    'Morphine',
    'Naloxone',
    'Sumatriptan',
    'Diphenhydramine',
    'Fexofenadine',
    'Aspirin',
    'Ibuprofen',
    'Celecoxib',
    'Acetaminophen',
    'Hydrocortisone',
    'Prednisone',
    'Beclomethasone',
    'Albuterol',
    'Azelastine',
    'Loratadine',
    'Phenylephrine',
    'Hydrocodone',
    'Dextromethorphan',
    'Famotidine',
    'Omeprazole',
    'Sucralfate',
    'Aluminum hydroxide',
    'Psyllium',
    'Docusate sodium',
    'Bisacodyl',
    'Magnesium hydroxide',
    'Ondansetron',
    'Dexamethasone',
    'Aprepitant',
    'Prochlorperazine',
    'Penicillin G',
    'Cephalexin',
    'Imipenem/cilastatin',
    'Vancomycin',
    'Tetracycline',
    'Erythromycin',
    'Clindamycin',
    'Gentamicin',
    'Sulfisoxazole',
    'Isoniazid',
    'Rifampin',
    'Ciprofloxacin',
    'Amphotericin B',
    'Itraconazole',
    'Influenza vaccine',
    'Insulin lispro',
    'Regular insulin',
    'NPH insulin',
    'Insulin glargine',
    'Metformin',
    'Glyburide',
    'Pioglitazone',
    'Repaglinide',
    'Levothyroxine',
    'Methimazole',
    'Desmopressin',
    'Vasopressin',
    'Furosemide',
    'Hydrochlorothiazide',
    'Spironolactone',
    'Nitrofurantoin',
    'Captopril',
    'Lorsartan',
    'Eplerenone',
    'Aliskiren',
    'Verapamil',
    'Nifedipine',
    'Hydralazine',
    'Propranolol',
    'Metoprolol',
    'Digoxin',
    'Dopamine',
    'Lovastatin',
    'Colesevelam',
    'Ezetimibe',
    'Nitroglycerin',
    'Clopidogrel',
    'Alteplase',
    'Ferrous sulfate',
    'Iron dextran',
    'Cyanocobalamin',
    'Folic acid',
    'Fluoxetine',
    'Venlafaxine',
    'Imipramine',
    'Selegiline',
    'Bupropion',
    'Diazepam',
    'Triazolam',
    'Zolpidem',
    'Buspirone',
    'Lithium',
    'Carbamazepine',
   
]